### ISSUE TITLE
[App Support]: Moodnotes - Mood Tracker

### ISSUE THREAD

**Issue by klee7941** [PlayCover/PlayCover#1070]
### App Store link

https://apps.apple.com/us/app/moodnotes-mood-tracker/id1019230398

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

Installs properly but will not launch. Icon appears on dock for a second but closes without app instance.

### Issue Language

- [X] Yes my issue is written in English
