### ISSUE TITLE
[Game Support]: Epic Seven "The application "Epic Seven" can't be opened."

### ISSUE THREAD

**Issue by depressed-blob** [PlayCover/PlayCover#1155]
### App Store link

took the ipa file from here: https://decrypt.day/app/id1322399438

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

-I've already disabled SIP
-Whenever I try to open Epic Seven it says "this application can not be opened".
I'm on Ventura 13.4.1 on an M2 MacBook Air

### Crash log

```shell
For some reason, it doesn't give a crash report.
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
What happens when you right click in Finder and click Open?

**Comment by TheMoonThatRises** [comment]
Use the nightly build of PlayCover. With that, you can enter (and log into) the app without disabling SIP.
