### ISSUE TITLE
[Game Support]: Atelier Resleriana - can't do anything after clicking the Ads tracking warning

### ISSUE THREAD

**Issue by arbiyanto** [PlayCover/PlayCover#1350]
### App Store link

https://apps.apple.com/tw/app/atelier-resleriana/id6467073639?l=en&uo=4

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [X] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

After clicking the popup banner asking for ad tracking permission (not a native popup from iOS but a guide), the game became unresponsive (nothing could be clicked), and could not continue entering the game.

What it looks like:
https://github.com/PlayCover/PlayCover/assets/17454427/fe3f50c4-8726-4806-bc02-82bba88071d6

Playcover version: 3.0.0 (618)

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by 931355011** [comment]
The same problem

**Comment by nullptrrr** [comment]
Same problem... Nothing I do will fix it
