### ISSUE TITLE
[Game Support]: Mahjong Soul tracking popup bug

### ISSUE THREAD

**Issue by vtu-dog** [PlayCover/PlayCover#328]
### App Store link

https://apps.apple.com/us/app/mahjong-soul/id1464872167

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [X] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Whenever you open the game, an orange popup asking the player to accept tracking will appear, along with a "Next" button. If you don't click "Next" fast enough, you might get logged out of the game, or even (rarely) crash the app.

The popup should not appear every time you open the game.

### Issue Language

- [X] Yes my issue is written in English
