### ISSUE TITLE
[Game Support]: Epic Seven

### ISSUE THREAD

**Issue by windmgc** [PlayCover/PlayCover#727]
### App Store link

https://apps.apple.com/us/app/id1322399438

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

The game showed an error indicating something like "missing necessary argument" every time I tried to click the `login` button.

The screenshot is in Chinese, however, you can see the error code on it.
<img width="263" alt="image" src="https://user-images.githubusercontent.com/2980074/213748241-11e24715-335d-4333-a3c7-2e0eae615a23.png">

The decrypted IPA file is downloaded from https://decrypt.day/app/id1322399438

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
You probably wants to follow the SIP/NVRAM procedure, or make a build with changes in #710 and see if it happens to work

**Comment by TheMoonThatRises** [comment]
Login now works with PlayChain enabled in the Nightly builds (under apps settings -> Bypasses).
