### ISSUE TITLE
[Game Support]: heavenburnsred Tracking Consent Error

### ISSUE THREAD

**Issue by Paimonm** [PlayCover/PlayCover#820]
### App Store link

https://apps.apple.com/kr/app/헤븐-번즈-레드/id1576831351

<img width="1479" alt="스크린샷 2023-02-27 23 27 17" src="https://user-images.githubusercontent.com/116867433/221591035-94b7e5bd-58b1-4f98-b1a8-514ef90534da.png">

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

It seems that the error occurs because the tracking consent pop-up does not appear.

### Issue Language

- [X] Yes my issue is written in English
